[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "ortools>=9.14.6206",
    "pandas>=2.3.2",
    "plotly>=6.3.0",
    "streamlit>=1.50.0",
]
